### ISSUE TITLE
Performance enhancements towards v2 release

### ISSUE THREAD

**Issue by vijayiyer05** [schnitzer-lab/extract-wip#6] opened 2021-10-15 22:40 UTC
Identify bottlenecks and implement performance enhancements using approaches such as parallelization, memory management, and/or C/C++ code integration. The [MATLAB Profiler](https://www.mathworks.com/help/matlab/matlab_prog/profiling-for-improving-performance.html) and/or [performance testing framework](https://www.mathworks.com/help/matlab/performance-testing-framework.html?searchHighlight=performance%20testing&s_tid=srchtitle) may be helpful tools.

Specific tasks include: 

- [x]  Orientation to codebase with EXTRACT project leader
- [x] First-pass reproduction of Figure 4 benchmarking from the [preprint](https://www.biorxiv.org/content/10.1101/2021.03.24.436279v1.full.pdf), w/ focus on reproducing the cell count from Fig4d
- [x] #1
- [x] Benchmarking on local machines & showing improvements
- [x] Benchmarking on various AMIs  & showing improvements

**Comment by manisha-sinha-appasamy** [comment] 2021-12-17 13:13
Just an update:

Here's my recent first pass reproduction of Fig. 4D on a Linux system (Ubuntu 20.04.3 LTS) with 24 GB RAM and GeForce GTX 1050 Ti GPU, MATLAB R2021b with the following config:
```
% Essentials, without these EXTRACT will give an error:
config.avg_cell_radius=6; 

% The movie is large, change the partitions if needed.
config.num_partitions_x=5;
config.num_partitions_y=5; 
```
![Fig4D_Ubuntu_RAM24GB_5x5partitions](https://user-images.githubusercontent.com/95078448/146539393-3d814b6f-e491-4a6a-bc95-f2eba4a9a3d6.png)

I will play around more with the different hyperparameters to improve the cell EXTRACTion.

I was also able to convert extract-public Tutorial 2 to be backwards compatible with MATLAB R2011a and run it on my old MBP with 4 GB RAM and GPU disabled (rest of the config remained the same as above):
```
config.use_gpu = false;
config.parallel_cpu = false;
```

Here's the reproduction of Fig 4D from that:
![Results_Fig4D_CPU](https://user-images.githubusercontent.com/95078448/146548215-7f613337-45ce-47dc-a30a-8cfbd9b12942.png)

I could be wrong here but to me it looks like the CPU version does a slightly better job of finding the really bright/big cells.

It will be interesting to see what the others get with similar/same config.

**Comment by vijayiyer05** [comment] 2022-01-21 19:10
@Yambottle, @manisha-sinha-appasamy
Per my discussion w/ @fatihdinc: the latest & greatest from the public repository has been merged here into extract-wip. The algorithm code is now stable.

Thus this repository is now ready for performance enhancement code submissions. Suggest that each team could submit changes as pull requests with review by the other (and I will try to take a look as well).

Where applicable, these may also later become suggestions (pull requests) to the public repository to help improve its performance.

**Closed** 2022-11-30 18:58 UTC
